import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Download, Github, Linkedin, Mail, Menu, X, ChevronRight, Command, CheckCircle2, ExternalLink } from 'lucide-react';
import { profile, skills, focus, projects, certifications } from './data/portfolio';

type Project = typeof projects[number];
const nav = ['Home','About','Skills','Projects','Experience','Education','Contact'];
const icon = { GitHub: Github, LinkedIn: Linkedin, Email: Mail };
function LinkButton({children, secondary=false, href='#'}:{children:React.ReactNode;secondary?:boolean;href?:string}) {return <a className={`button ${secondary?'secondary':''}`} href={href}>{children}</a>}
function ProjectVisual({project}:{project:Project}) { return <div className={`project-visual ${project.id}`} aria-hidden="true">{project.id==='pranawell'?<><div className="mock-nav">pranawell <span>● ●</span></div><div className="wellness-card"><small>Daily wellness</small><strong>Good morning, Prasanna</strong><div className="progress"><i></i></div><div className="mini-grid"><b>Hydration</b><b>Balance</b><b>Activity</b></div></div><div className="leaf"></div></>:<><div className="farm-sun"></div><div className="plant-card"><small>KRISHI AI</small><strong>Plant health<br/>insights, simply.</strong><div className="scan"></div><span>Analyze crop →</span></div><div className="hill hill-a"></div><div className="hill hill-b"></div></>}</div>}
function CaseStudy({project,onClose}:{project:Project;onClose:()=>void}) {const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{closeRef.current?.focus(); const h=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[onClose]);return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><article className="modal" role="dialog" aria-modal="true" aria-labelledby="case-title" onMouseDown={e=>e.stopPropagation()}><button ref={closeRef} className="close" onClick={onClose} aria-label="Close case study"><X/></button><ProjectVisual project={project}/><p className="kicker">CASE STUDY · {project.status.toUpperCase()}</p><h2 id="case-title">{project.title}</h2><p className="modal-lede">{project.description}</p><div className="case-grid"><div><h3>01 — The problem</h3><p>{project.detail.problem}</p><h3>02 — The solution</h3><p>{project.detail.solution}</p><h3>03 — Challenge</h3><p>{project.detail.challenge}</p></div><div><h3>Architecture</h3><ol className="architecture">{project.detail.architecture.map(x=><li key={x}>{x}</li>)}</ol><h3>Learning outcomes</h3><p>{project.detail.learning}</p></div></div><h3>Core capabilities</h3><div className="feature-list">{project.features.map(([name,description])=><div key={name}><b>{name}</b><span>{description}</span></div>)}</div><h3>Technology stack</h3><div className="chips">{project.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="modal-actions"><LinkButton href={project.githubUrl}><Github size={16}/> GitHub</LinkButton><LinkButton secondary href={project.liveUrl}><ExternalLink size={16}/> Live demo</LinkButton></div></article></div>}
function App(){
 const [open,setOpen]=useState(false),[caseProject,setCaseProject]=useState<Project|null>(null),[palette,setPalette]=useState(false),[submitted,setSubmitted]=useState(false); const [active,setActive]=useState('Home');
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);
 const go=(item:string)=>{setActive(item);setOpen(false);setPalette(false);document.getElementById(item.toLowerCase())?.scrollIntoView({behavior:'smooth'});};
 return <><div className="page-glow glow-one"/><div className="page-glow glow-two"/><header><a href="#home" className="logo" onClick={()=>go('Home')}><span>P</span> Prasanna</a><nav aria-label="Primary navigation">{nav.map(n=><button className={active===n?'active':''} onClick={()=>go(n)} key={n}>{n}</button>)}</nav><div className="head-actions"><a href={profile.githubUrl} aria-label="GitHub"><Github/></a><a href={profile.linkedinUrl} aria-label="LinkedIn"><Linkedin/></a><a className="resume-link" href={profile.resumeUrl}><Download size={14}/> Resume</a><button className="menu" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button></div></header>
 {open&&<div className="mobile-nav" role="dialog" aria-modal="true" aria-label="Mobile navigation"><button onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button>{nav.map(n=><a onClick={()=>go(n)} key={n}>{n}<ChevronRight/></a>)}</div>}
 <main><section id="home" className="hero container"><div className="portrait-wrap"><div className="orbit orbit1"></div><div className="orbit orbit2"></div><div className="portrait"><img src="/src/assets/profile-photo.jpg" alt="Laxmi Prasanna Chandragiri"/></div><div className="code-label">&lt; developer /&gt;</div></div><div className="hero-copy"><p className="kicker"><i/> HELLO, I'M</p><h1>Laxmi Prasanna Chandragiri<span>.</span></h1><h2>{profile.role}</h2><p className="intro">{profile.intro}</p><p className="subintro">{profile.bio}</p><div className="socials"><a href={profile.githubUrl}><Github/> GitHub</a><a href={profile.linkedinUrl}><Linkedin/> LinkedIn</a><a href={profile.email}><Mail/> Email</a></div><div className="hero-buttons"><LinkButton href="#projects">View My Projects <ArrowUpRight size={16}/></LinkButton><LinkButton secondary href={profile.resumeUrl}><Download size={16}/> Download Resume</LinkButton></div></div><div className="focus-strip">{focus.map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></section>
 <section id="about" className="section container about"><div><p className="kicker">01 / ABOUT</p><h2>A curious builder, focused on <em>useful work.</em></h2></div><div className="about-copy"><p>I’m a Computer Science & Engineering student interested in software engineering, AI/ML, and full-stack development. I enjoy turning practical problems into clear, considered digital products while steadily improving my programming and problem-solving skills.</p><div className="profile-card"><span>DEVELOPER PROFILE</span><dl><div><dt>Focus</dt><dd>Software Development</dd></div><div><dt>Interests</dt><dd>AI / ML · Full Stack · Problem Solving</dd></div><div><dt>Currently learning</dt><dd>DSA · System Design · Cloud / Deployment</dd></div></dl></div></div></section>
 <section id="skills" className="section container"><p className="kicker">02 / TOOLKIT</p><h2>Technology, with <em>intention.</em></h2><div className="skill-grid">{(skills as [string, string[]][]).map(([title,items],i)=><article className="skill-card" key={title}><span>0{i+1}</span><h3>{title}</h3><div>{items.map(s=><b key={s}>{s}</b>)}</div></article>)}</div></section>
 <section id="projects" className="section container projects"><div className="section-heading"><div><p className="kicker">03 / FEATURED PROJECTS</p><h2>Built around real <em>problems.</em></h2></div><p>Selected software prototypes bringing together product thinking, machine learning, and thoughtful development.</p></div><div className="project-grid">{projects.map(project=><article className="project-card" key={project.id}><ProjectVisual project={project}/><div className="project-info"><p className="kicker">{project.category}</p><h3>{project.title}</h3><em>{project.tagline}</em><p>{project.description}</p><div className="chips">{project.technologies.slice(0,4).map(t=><span key={t}>{t}</span>)}</div><div className="project-actions"><a href={project.githubUrl}><Github size={15}/> GitHub</a><a href={project.liveUrl}><ExternalLink size={15}/> Live demo</a><button onClick={()=>setCaseProject(project)}>View details <ArrowUpRight size={16}/></button></div></div></article>)}</div></section>
 <section id="experience" className="section container timeline"><p className="kicker">04 / EXPERIENCE & LEARNING</p><h2>Growing through <em>practice.</em></h2><div className="timeline-row"><span>2026</span><div><h3>Web Development Intern</h3><p>Axlero Solutions · Remote</p></div><p>July 2026 – October 2026</p></div><div className="credentials">{certifications.map(c=><div key={c}><CheckCircle2/> {c}</div>)}</div></section>
 <section id="education" className="section container education"><p className="kicker">05 / EDUCATION</p><div className="education-card"><div><span>B.TECH</span><h2>Computer Science<br/>& Engineering</h2><p>Priyadarshini Institute of Science & Technology for Women</p></div><div><small>CGPA</small><strong>7.8 <i>/ 10</i></strong></div></div></section>
 <section id="contact" className="section container contact"><p className="kicker">06 / CONTACT</p><h2>Let's build something <em>meaningful.</em></h2><p>Have an opportunity, idea, or project in mind? Let's connect.</p><div className="contact-grid"><div><a href={profile.email}>Email me <ArrowUpRight/></a><a href={profile.githubUrl}>GitHub <ArrowUpRight/></a><a href={profile.linkedinUrl}>LinkedIn <ArrowUpRight/></a></div><form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@example.com"/></label><label>Subject<input required name="subject" placeholder="What's this about?"/></label><label>Message<textarea required name="message" placeholder="Tell me a little about it."/></label><button className="button" type="submit">{submitted?'Message ready to send':'Prepare message'} <ArrowUpRight size={16}/></button>{submitted&&<p className="form-note">Thanks — email delivery is not configured yet. Please use the email link to send your message.</p>}</form></div></section></main>
 <footer className="container"><a href="#home" className="logo"><span>P</span> Laxmi Prasanna Chandragiri</a><p>Building, learning, and shipping.</p><p>© 2026 Laxmi Prasanna Chandragiri. All rights reserved.</p></footer>
 <button className="palette-trigger" onClick={()=>setPalette(true)} aria-label="Open command palette"><Command/> <span>Menu</span><kbd>⌘ K</kbd></button>
 {palette&&<div className="modal-backdrop" onMouseDown={()=>setPalette(false)}><div className="palette" role="dialog" aria-modal="true" aria-label="Quick navigation" onMouseDown={e=>e.stopPropagation()}><p>GO TO</p>{nav.map(x=><button key={x} onClick={()=>go(x)}>{x}<ChevronRight/></button>)}<a href={profile.resumeUrl}><Download/>Resume</a><a href={profile.githubUrl}><Github/>GitHub</a><a href={profile.linkedinUrl}><Linkedin/>LinkedIn</a></div></div>}
 {caseProject&&<CaseStudy project={caseProject} onClose={()=>setCaseProject(null)}/>}</>}
export default App;
